image: klakegg/hugo:alpine-ci

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_BASE_URL: 'https://sosiris-templates.gitlab.io/hugo-geekdoc/'

before_script:
  - apk add --update --no-cache brotli git
  - hugo --gc --minify -b ${HUGO_BASE_URL}

test:
  script:
  - echo "Test build completed."
  except:
  - main

pages:
  script:
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
  only:
  - main
